version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - penalty_network
  penaltyapp:
    container_name: penalty-app
    build:
      context: .
    ports:
      - '1200:1200'
    depends_on:
      - postgres
    networks:
      - penalty_network
    environment:
      MESSAGE_BROKER_URI: redpanda-0:9092
      GRPC_ADDRESS: 1200
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_NAME: dbname
      DB_PASSWORD: password

volumes:
  postgres_data:

networks:
  penalty_network:
    driver: bridge
