[package]
name = "booking"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13"
tokio = { version = "1.4", features = ["rt-multi-thread", "macros", "sync", "time"] }
tonic = "0.12"

[build-dependencies]
tonic-build = "0.12"